---
title: "ice 4"
author: "Sicheng Xu"
date: "3/21/2022"
output: html_document
---

library(tidyverse)
interest <- read_csv("/Users/CodyXu/R/interest.csv")
difficulty <- read_csv("/Users/CodyXu/R/difficulty.csv")
head(interest)
head(difficulty)

interest_means_t <- t(interest_means)
difficulty_means_t <- t(difficulty_means)
rownames(interest_means_t) <- colnames(interest_means)
rownames(difficulty_means_t) <- colnames(difficulty_means)
setNames(interest_means_t, c("interest"))
setNames(difficulty_means_t, c("diffculty"))
row.names(interest_means_t)[row.names(interest_means_t) == "prediction.interest"] <- "prediction"
row.names(interest_means_t)[row.names(interest_means_t) == "nlp.interest"] <- "nlp"
row.names(interest_means_t)[row.names(interest_means_t) == "sna.interest"] <- "sna"
row.names(interest_means_t)[row.names(interest_means_t) == "neural.interest"] <- "neural"
row.names(interest_means_t)[row.names(interest_means_t) == "viz.interest"] <- "viz"
row.names(interest_means_t)[row.names(interest_means_t) == "loop.interest"] <- "loop"
row.names(interest_means_t)[row.names(interest_means_t) == "sql.interest"] <- "sql"
row.names(difficulty_means_t)[row.names(difficulty_means_t) == "prediction.difficulty"] <- "prediction"
row.names(difficulty_means_t)[row.names(difficulty_means_t) == "nlp.difficulty"] <- "nlp"
row.names(difficulty_means_t)[row.names(difficulty_means_t) == "sna.difficulty"] <- "sna"
row.names(difficulty_means_t)[row.names(difficulty_means_t) == "neural.difficulty"] <- "neural"
row.names(difficulty_means_t)[row.names(difficulty_means_t) == "viz.difficulty"] <- "viz"
row.names(difficulty_means_t)[row.names(difficulty_means_t) == "loop.difficulty"] <- "loop"
row.names(difficulty_means_t)[row.names(difficulty_means_t) == "sql.difficulty"] <- "sql"
difficulty_interest <- cbind(difficulty_means_t, interest_means_t)
difficulty_interest <- as.data.frame(difficulty_interest)
difficulty_interest <- setNames(difficulty_interest, c("difficulty","interest"))
difficulty_interest

p <- ggplot(difficulty_interest, aes(difficulty,
                                     interest,
                                     label = rownames(difficulty_interest))) +
  geom_point() +
  geom_text(nudge_x = 0.02, nudge_y = 0.02)

p
x <- difficulty_interest[1,]
distance <- data.frame(d = rep(NA, 7), row.names = row.names(difficulty_interest))

for (i in 1:nrow(difficulty_interest)) {
  y <- difficulty_interest[i,] #pick one of the rows as the target item
  d <- dist(rbind(x, y)) # measure the euclidean distance (by default) and assign to d
  distance[i, 1] <- d # insert the calculated distance to the distance data frame
}
arrange(distance, d)

library(lsa)
di <- difficulty_interest %>% 
  as.matrix() %>% 
  t()
di_sim <- cosine(di)
diag(di_sim) <- NA
item <- "prediction"
head(rownames(di_sim[order(di_sim[item,], decreasing = TRUE),]), n = 4)

### COLLABORATIVE FILTER
interest <- column_to_rownames(interest, var = "id") #move the id to row names
interestMatrix <- interest %>% 
  as.matrix() %>% t()
interestSim <- cosine(interestMatrix)
diag(interestSim) <- NA
person <- "s5"
head(rownames(interestSim[order(interestSim[person,], decreasing = TRUE),]))

